name: linux-build

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: download dependencies
      run: |
        sudo apt update
        sudo apt install -y libsodium-dev libgtkmm-4.0-dev
    - name: build server
      run: |
        cd server
        make
    - name: build app
      run: |
        cd src
        make