name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download dependencies
      run: |
        sudo apt update
        sudo apt install -y libncurses5-dev libncursesw5-dev
    - name: build server
      run: |
        cd server
        make
    - name: build app
      run: |
        cd src
        make
