name: MSYS2
on: [push, pull_request]

jobs:
  windows_build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git make zip mingw-w64-ucrt-x86_64-gtkmm-4.0 mingw-w64-ucrt-x86_64-libsodium mingw-w64-ucrt-x86_64-toolchain
      - name: CI-Build
        run: |
          cd src
          make win
          make win_release

  make_artifact:
    runs-on: ubuntu-latest
    needs: windows_build
    environment: windows-release-manual
    steps:
      - uses: actions/checkout@v3
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win_release
          path: src/blink_win.zip
          if-no-files-found: error
          overwrite: true